### ISSUE TITLE
Any chance to update ?

### ISSUE THREAD

**Issue by marifrahman** [fontis/fontis_anzegate#7]
Hi,
I see the supported magento platforms are pretty old. Is there a chance to update it to support the latest version ?

**Comment by chnorton** [comment]
The list of supported platforms only shows the versions of Magento which we've either tested ourselves or had reports from users that the extension works without modification. Given that there have been very few changes to the way payment methods work since the very earliest versions of Magento, it might be worth testing it to see if it works as-is.

If it does work, let us know and we can update the list, and if doesn't then we're always happy to accept pull requests.
